---
title: "Análise da base de dados no IMDB"
author:
  - name: Tiago Adrego
  - name: Sílvia Fonseca
  - name: Joana Pereira
---

# Carregamento das bibliotecas necessárias
```{r load-packages}
library(tidyverse)
library(janitor)
library(DataExplorer)
library(dplyr)
library(factoextra)
library(GGally)
library(tidyr)
library(lubridate)
library(stringr)
library(ggplot2)
library(esquisse)
library(corrplot)
```

# Importação de dados
```{r load-dataset}
movies <- read_csv("imdb_movies.csv",
                   col_types = list(
                     col_character(),
                     col_date(format = "%m/%d/%Y"),
                     col_double(),
                     col_character(),
                     col_character(),
                     col_character(),
                     col_character(),
                     col_character(),
                     col_character(),
                     col_double(),
                     col_double(),
                     col_character()
                     )
                  )
```

# Limpeza de dados
```{r unnest-genres}
movies_unnested  <- movies |>
  separate_rows(genre, sep = ",") |>
  mutate(genre = str_trim(genre)) |>
  pivot_wider(names_from = genre,
              values_from = genre,
              values_fn = length,
              values_fill = 0) |>
  clean_names() |>
  mutate(across(drama:tv_movie, ~ replace(., na != 0 & . == 0, NA))) |>
  select(-na)
```

# Exploratory Data Analysis

```{r check-data}
glimpse(movies_unnested)
summary(movies_unnested)
DataExplorer::create_report(movies_unnested)
```

# Descritivas
```{r Descriptives}
##SINTO QUE TODO ESTE CHUNK PODIA SER SIMPLIFICADO ;)

sum(movies_unnested$budget_x)
sum(movies_unnested$revenue)
median(movies_unnested$budget_x)
median(movies_unnested$revenue)
IQR(movies_unnested$budget_x)
IQR(movies_unnested$revenue)
mean(movies_unnested$budget_x)
mean(movies_unnested$revenue)
sd(movies_unnested$budget_x)
sd(movies_unnested$revenue)

table(movies_unnested$status)
table(movies_unnested$country)
table(movies_unnested$orig_lang)
table(movies_unnested$country, movies_unnested$status)

table(movies_unnested$drama)
table(movies_unnested$action)
table(movies_unnested$science_fiction)
table(movies_unnested$adventure)
table(movies_unnested$animation)
table(movies_unnested$family)
table(movies_unnested$fantasy)
table(movies_unnested$comedy)
table(movies_unnested$thriller)
table(movies_unnested$crime)
table(movies_unnested$horror)
table(movies_unnested$mystery)
table(movies_unnested$history)
table(movies_unnested$war)
table(movies_unnested$documentary)
table(movies_unnested$romance)
table(movies_unnested$music)
table(movies_unnested$western)
table(movies_unnested$tv_movie)

```


```{r Score Revised & Descriptives}

##Remove all zeros from the score? Considering they were not reviewed yet.

##MUITA CONFUSA AQUI, NÃO SEI SE POSSO FAZER ESTA ASSUMPTION, MAS ACHO MUITO ESTRANHO TER UM 0 NUM SCORE DE REVIEWS. SE NÃO ACHAREM NECESSÁRIO, NÃO SE CONSIDERA ESTE PASSO.

mean_score <- mean(movies_unnested$score, na.rm = TRUE)

movies_unnested$score_revised <- ifelse(movies_unnested$score == 0, mean_score, movies_unnested$score)

glimpse(movies_unnested)

median(movies_unnested$score_revised, na.rm = TRUE)
IQR(movies_unnested$score_revised, na.rm = TRUE)
mean(movies_unnested$score_revised, na.rm = TRUE)
sd(movies_unnested$score_revised, na.rm = TRUE)
min(movies_unnested$score_revised, na.rm = TRUE)
max(movies_unnested$score_revised, na.rm = TRUE)

summary(movies_unnested$score_revised)
is.numeric(movies_unnested$score_revised)

glimpse(movies_unnested)
summary(movies_unnested)

```

```{r}
#Aqui vai ser a classificação

```

```{r Group By Descriptives}
##COMO PODEREMOS FAZER AQUI O MESMO PARA GENRE?

movies_unnested %>%
  group_by(country) %>%
  summarize(meanbudget_bycountry = mean(budget_x),
            meanrevenue_bycountry = mean(revenue),
            maxbudget_bycountry = max(budget_x),
            maxrevenue_bycountry = max(revenue),
            meanscore_bycountry = mean(score_revised, na.rm = TRUE))%>%
  ungroup

```


# Visuals
```{r visualizations}
##FAZER NO ESQUISSE?
```


# Deal Missing Values
```{r missing values}
#Replace by the average

movies_readyforanalysis <-
  movies_unnested %>%
  replace_na(list(budget_x = round(mean(movies_unnested$budget_x, na.rm = TRUE)),
                  revenue = round(mean(movies_unnested$revenue, na.rm = TRUE))))
                   
glimpse(movies_readyforanalysis)
summary(movies_readyforanalysis)
```


# Normal Distribution
```{r normal distribution}
##NÃO PERCEBO PORQUE AQUI DÁ ERRO!!

shapiro.test(movies_readyforanalysis$score_revised)
shapiro.test(movies_readyforanalysis$budget_x)
shapiro.test(movies_readyforanalysis$revenue)

```


# Correlações

```{r correlations}

movies_readyforanalysis_numeric <-
  movies_readyforanalysis %>%
  select (budget_x,revenue,score_revised)
  
correlation_matrix <-
  cor(movies_readyforanalysis_numeric, method = "pearson")

print(correlation_matrix)

corrplot(correlation_matrix)

```

# Clustering
```{r select attributes & zscores}

#Select attributes
#The same used for correlations

summary(movies_readyforanalysis_numeric)
glimpse(movies_readyforanalysis_numeric)


#Z-Scores

movies_readyforanalysis_numeric_standardized <-
  movies_readyforanalysis_numeric %>%
  mutate(zscore_budget = (budget_x - mean(budget_x,na.rm = T))/sd(budget_x),
         zscore_revenue = (revenue - mean(revenue, na.rm = T))/sd(revenue),
         zscore_score_revised = (score_revised - mean(score_revised, na.rm = T))/sd(score_revised)) %>%
    select(zscore_budget, zscore_revenue, zscore_score_revised)
      
movies_readyforanalysis_numeric_standardized

```
 
```{r clustering}

resultado_kmeans <- kmeans(movies_readyforanalysis_numeric_standardized, centers = 3)
movies_readyforanalysis_numeric_standardized$cluster <- as.character(resultado_kmeans$cluster)

ggplot(movies_readyforanalysis_numeric_standardized) +
  aes(
    x = zscore_revenue,
    y = zscore_score_revised,
    colour = cluster
  ) +
  geom_point(shape = "circle", size = 1.5) +
  scale_color_hue(direction = 1) +
  theme_minimal()

ggplot(movies_readyforanalysis_numeric_standardized) +
  aes(
    x = zscore_budget,
    y = zscore_score_revised,
    colour = cluster
  ) +
  geom_point(shape = "circle", size = 1.5) +
  scale_color_hue(direction = 1) +
  theme_minimal()

ggplot(movies_readyforanalysis_numeric_standardized) +
  aes(x = zscore_budget, y = zscore_revenue, colour = cluster) +
  geom_point(shape = "circle", size = 1.5) +
  scale_color_hue(direction = 1) +
  theme_minimal()
```

```{r clusters centers}

centers <- as.data.frame(resultado_kmeans$centers)
centers$cluster <- rownames(resultado_kmeans$centers)

ggparcoord(centers, columns = 1:3, groupColumn = 4) 
```

```{r better hyper-parameters}

fviz_nbclust(movies_readyforanalysis_numeric_standardized, kmeans, method = "wss", k.max = 10)

```

```{r after elbow method}
# Choose 4 clusters

resultado_kmeans <- kmeans(movies_readyforanalysis_numeric_standardized, centers = 4)
movies_readyforanalysis_numeric_standardized$cluster <- as.character(resultado_kmeans$cluster)

centers <- as.data.frame(resultado_kmeans$centers)
centers$cluster <- rownames(resultado_kmeans$centers)

ggparcoord(centers, columns = 1:3, groupColumn = 4) 

##Name of Clusters & Examples of Movies
# Cluster 1-
# Cluster 2-
# Cluster 3-
# Cluster 4-

```


